# Generated by Django 3.1.3 on 2023-04-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pynuts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='create_date',
        ),
    ]
