# Generated by Django 3.1.3 on 2023-04-17 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pynuts', '0002_remove_question_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptresponse',
            name='product',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
